/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iPoolAddressProviderSol from "./IPoolAddressProvider.sol";
export type { iPoolAddressProviderSol };
export type { FlashLoanReceiverBase } from "./FlashLoanReceiverBase";
export type { IFlashLoanReceiver } from "./IFlashLoanReceiver";
export type { IPool } from "./IPool";
